# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-09 15:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doacoes_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_conclusao', models.DateTimeField(null=True)),
                ('conclusao', models.BooleanField()),
                ('foto', models.CharField(max_length=1000)),
                ('descricao', models.CharField(max_length=500)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doacoes_app.Produto')),
            ],
        ),
    ]
