# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-09 15:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doacoes_app', '0002_doacao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doacao',
            name='produto',
        ),
        migrations.DeleteModel(
            name='Doacao',
        ),
    ]
