# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-09 15:24
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('doacoes_app', '0003_auto_20170809_1523'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_conclusao', models.DateTimeField(null=True)),
                ('conclusao', models.BooleanField()),
                ('foto', models.CharField(max_length=1000)),
                ('descricao', models.CharField(max_length=500)),
                ('doador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doador', to=settings.AUTH_USER_MODEL)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produto', to='doacoes_app.Produto')),
                ('receptor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receptor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
