# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-09 16:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('doacoes_app', '0007_auto_20170809_1640'),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idade', models.PositiveIntegerField(null=True)),
                ('telefone1', models.CharField(max_length=20)),
                ('telefone2', models.CharField(max_length=20)),
                ('endereco', models.CharField(max_length=300)),
                ('tipo_usuario', models.CharField(max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
