# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-11 22:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doacoes_app', '0008_perfil'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doacao',
            name='doador',
        ),
        migrations.RemoveField(
            model_name='doacao',
            name='produto',
        ),
        migrations.RemoveField(
            model_name='doacao',
            name='receptor',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='user',
        ),
        migrations.DeleteModel(
            name='Doacao',
        ),
        migrations.DeleteModel(
            name='Perfil',
        ),
    ]
