# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-11 22:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('doacoes_app', '0009_auto_20170811_2237'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_criacao', models.DateField(default=django.utils.timezone.now)),
                ('data_conclusao', models.DateField(null=True)),
                ('conclusao', models.BooleanField()),
                ('foto', models.CharField(max_length=1000)),
                ('descricao', models.CharField(max_length=500)),
                ('doador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doador', to=settings.AUTH_USER_MODEL)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produto', to='doacoes_app.Produto')),
                ('receptor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receptor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idade', models.PositiveIntegerField(null=True)),
                ('telefone1', models.CharField(max_length=20)),
                ('telefone2', models.CharField(max_length=20)),
                ('uf', models.CharField(max_length=2)),
                ('cidade', models.CharField(max_length=30)),
                ('endereco', models.CharField(max_length=300)),
                ('tipo_usuario', models.CharField(max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
