# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-15 20:37
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doacoes_app', '0010_doacao_perfil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doacao',
            name='data_criacao',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
