# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-18 21:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doacoes_app', '0011_auto_20170815_2037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doacao',
            name='conclusao',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='doacao',
            name='data_conclusao',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='doacao',
            name='foto',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='doacao',
            name='receptor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receptor', to=settings.AUTH_USER_MODEL),
        ),
    ]
