# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-19 21:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doacoes_app', '0012_auto_20170818_2110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doacao',
            name='foto',
            field=models.CharField(max_length=1000),
        ),
    ]
