# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-21 14:39
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doacoes_app', '0014_auto_20170821_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doacao',
            name='data_criacao',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='doacao',
            name='descricao',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='doacao',
            name='doador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doador', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='doacao',
            name='produto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='produto', to='doacoes_app.Produto'),
        ),
    ]
