# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-21 15:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('doacoes_app', '0016_auto_20170821_1451'),
    ]

    operations = [
        migrations.AddField(
            model_name='doacao',
            name='doador',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doador', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='doacao',
            name='produto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='produto', to='doacoes_app.Produto'),
        ),
    ]
